repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
      # - id: ruff-format
# repos:
#   - repo: local
#     hooks:
#       - id: ruff-check
#         name: ruff-check
#         entry: bash -c 'python -m ruff check . || (echo "" && echo "Lint check failed. Run '"'"'python -m ruff check .'"'"' to see errors and fix them manually." && exit 1)'
#         language: python
#         additional_dependencies: ["ruff==0.15.9"]
#         pass_filenames: false
#         always_run: true
